### PR TITLE
WIP: 3.0.2

### PR DESCRIPTION
**Pull request by hmaarrfk**
Forked from https://github.com/conda-forge/openssl-feedstock/pull/84#issuecomment-1072908608
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by h-vetinari** [comment]
Looking good! I didn't dare delete the test, but I think that - all things considered - that would be a better trade-off than not publishing the CVE-fixes.

**Comment by hmaarrfk** [comment]
Right. I didn't want to push to your branch for a 1 liner. 

I did test the full tests locally and it worked.

So I think your suspicion is right that it is failing due to emulation.

**Comment by h-vetinari** [comment]
Feel free to push https://github.com/conda-forge/openssl-feedstock/pull/85/commits/4484ddf170c643c69cda556239875d8fb9c9d9d4 to #84 and #83 (and the cross compilation changes if you want). 🙃

**Comment by h-vetinari** [comment]
And thanks for testing locally, that should allay any remaining suspicions.

**Comment by hmaarrfk** [comment]
I should say that i tested the natively compiled version locally.

**Comment by hmaarrfk** [comment]
@conda-forge-admin please rerender

**Comment by h-vetinari** [comment]
Thanks for testing this! If it works, feel free to force-push into #84 (if you want to replace the other commits).

**Pull request closed without merging**
