### PR TITLE
Split out static libraries and update to 1.1.1c

### LINKED ISSUE #45: Split out static libraries
The static libraries are non-negligible in size:

```
$ du -hc lib/libssl.a lib/libcrypto.a
776K    lib/libssl.a
4.1M    lib/libcrypto.a
4.8M    total
```

If possible, it would be useful to split out the static libraries into separate packages (especially important for installation in a docker container).

### PR DESCRIPTION
**Pull request by jjhelmus**
Split out the static libraries into a new package named libopenssl-static on linux and osx.
Update to the 1.1.1c release on OpenSSL.

closes #45

### CODE REVIEW

**Comment by jjhelmus** [comment]
@conda-forge-admin, please rerender

**Comment by jjhelmus** [comment]
The test failure on linux-64 is related to using conda-build 3.18.4. The split package builds fine using conda-build 3.17.8.

**Comment by jjhelmus** [comment]
@conda-forge-admin, please rerender

**Comment by CJ-Wright** [comment]
Do we need to move the pin for this?

**Comment by jjhelmus** [comment]
> Do we need to move the pin for this?

No, building with openssl 1.1.1a will provide compatibility with all releases in the 1.1.1{a-z} line.

**Comment by CJ-Wright** [comment]
awesome!

**Pull request merged**
