### PR TITLE
Build legacy comaptibility for windows

### LINKED ISSUE #95: @conda-forge-admin please rerender
### Comment:

_No response_

### PR DESCRIPTION
**Pull request by conda-forge-linter**
@h-vetinari this comment explains that the legacy bindings are used in cyrptography python
https://github.com/pyca/cryptography/issues/6818#issuecomment-1022434420

### CODE REVIEW

**Comment by hmaarrfk** [comment]
I'm not really sure this did anything. I tried to test locally and it didn't change the results of cryptography

**Comment by h-vetinari** [comment]
Should we try merging nevertheless?

**Comment by hmaarrfk** [comment]
> Should we try merging nevertheless?

I don't want to merge "a legacy flag" prolonging the delay of incompatibility without a positive effect.

Personally, I don't understand why things are not failing for linux or osx.

Maybe cryptography is gracefully failing there, but not gracefully failing for windows? in which case, we should help them instead of building legacy for windows.

**Comment by h-vetinari** [comment]
> Maybe cryptography is gracefully failing there, but not gracefully failing for windows? in which case, we should help them instead of building legacy for windows.

The cryptography [code](https://github.com/pyca/cryptography/blob/37.0.2/src/cryptography/hazmat/bindings/openssl/binding.py#L167-L178) you had [linked](https://github.com/conda-forge/cryptography-feedstock/pull/98#issuecomment-1134023205) explicitly requires the legacy provider.

> Personally, I don't understand why things are not failing for linux or osx.

No idea either, but if the legacy provider is missing, we should build it.

> I don't want to merge "a legacy flag" prolonging the delay of incompatibility without a positive effect.

It's not a legacy flag. I'm not sure how closely you followed the OpenSSL 3.0 effort, but a key part was factoring things into pluggable providers. One dogfooding exercise was to put all the cryptographic cruft into a legacy provider that will (on an absurdly long timeline) eventually be removed, but it's still absolutely necessary for feature parity when migrating from OpenSSL 1.1.1 to OpenSSL 3.0.0

**Comment by h-vetinari** [comment]
@conda-forge-admin, please rerender

**Pull request closed without merging**
