### PR TITLE
Build long prefix package using conda-build 2.x

### PR DESCRIPTION
**Pull request by jjhelmus**

### CODE REVIEW

**Comment by jjhelmus** [comment]
The linter seems to be complaining about the link to the license in the line: `license: Apache-style (http://www.openssl.org/source/license.html)`.  I think this should be ignored as this URL is important to keep in the metadata.

**Comment by jakirkham** [comment]
Is it? We are including the license file. I don't know if we still need the link if we have the license file in the package.

**Comment by jjhelmus** [comment]
The link is included on Anaconda.org for anyone who wants to examine the license prior to installing the package.  The license file is not available through the Anaconda.org UI and therefore not discoverable by the users (as far as I know) without downloading the package.

**Comment by jakirkham** [comment]
> The link is included on Anaconda.org for anyone who wants to examine the license prior to installing the package.

Even in that case, I'm not really sure that this is so helpful. See for instance what Anaconda.org does with the license in this case (bottom left corner). Trying to get the link out of there isn't exactly fun.

screen shot 2016-11-29 at 12 27 14

> The license file is not available through the Anaconda.org UI and therefore not discoverable by the users (as far as I know) without downloading the package.

TBH this sounds like a reasonable request of upstream.

Though it still seems ok for us to download and inspect the license file. This is what one would need to do with a package from PyPI anyways. Is there a reason not to do this that you can think of?

**Comment by jjhelmus** [comment]
I'm fine removing the URL is that is what is desired but I think it should be done in a separate PR.  I'm currently trying to re-build as many packages as possible with conda-build 2.x and would rather not have to solve other unrelated feedstock issues at the same time.

**Comment by jakirkham** [comment]
Not a problem. Was only trying to understand the original [assertion]( https://github.com/conda-forge/openssl-feedstock/pull/8#issuecomment-263628970 ). Feel free to raise a `conda-smithy` issue and we can discuss it there later.

**Comment by jjhelmus** [comment]
Sorry for being short with you yesterday @jakirkham, you did not deserve that.  I really appreciate your help reviewing PRs and catching issues. 

The question of the license text is important and should be resolved but I am still inclined to defer it until later.

**Comment by jakirkham** [comment]
> Sorry for being short with you yesterday @jakirkham, you did not deserve that.  I really appreciate your help reviewing PRs and catching issues.

Not a problem. I should have moved the discussion into a new issue.

> The question of the license text is important and should be resolved but I am still inclined to defer it until later.

Sure. It is lower priority than upgrading `conda-build`.

**Comment by jakirkham** [comment]
Opened PR ( https://github.com/conda-forge/openssl-feedstock/pull/10 ) to remove the link to the license. Please share your thoughts.

**Pull request merged**
