### PR TITLE
Made the static package depend on the dynamic one to get headers

### PR DESCRIPTION
**Pull request by JohanMabille**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by JohanMabille** [comment]
@h-vetinari @jakirkham If any of you has time to review it, I need to fix a bunch of static builds on conda-forge, and this one is the first step.

**Review by h-vetinari — APPROVED** [review]
LGTM

**Comment by h-vetinari** [comment]
> @h-vetinari @jakirkham If any of you has time to review it, I need to fix a bunch of static builds on conda-forge, and this one is the first step.

This looks very vanilla, so I'm merging it. Thanks for the PR!

**Comment by JohanMabille** [comment]
Thanks for the merge ;)

**Pull request merged**
