### PR TITLE
OpenSSL 1.1.1n

### LINKED ISSUE #82: Branch for 1.1.1 to capture missing releases
I realized that conda-forge is two releases behind for 1.1.1 (due to the default bot behaviour treating only the newest release), including the latest CVE fix in 1.1.1n, see e.g. [here](https://www.openssl.org/news/openssl-1.1.1-notes.html).

This should IMO be fixed with higher-than-usual urgency, not least since large swaths of conda-forge are still bound to `openssl <3` due to https://github.com/conda-forge/cryptography-feedstock/pull/80.

Could someone from @conda-forge/core create a branch for 1.1.1 at 26f7bd0059d2415ec5ac962d4906127d4c557de0? If people prefer a PR to join as maintainer (and then creating the branch myself), I can do that too.

### PR DESCRIPTION
**Pull request by h-vetinari**
Closes #82 

Still needs to add
```
bot:
  abi_migration_branches:
  - 1.1.1
```
on main (AFAIU), but will do that with another PR (edit: done in #84).

### CODE REVIEW

**Comment by h-vetinari** [comment]
No idea what's causing the problems on OSX, raised https://github.com/conda/conda-build/issues/4397

**Comment by h-vetinari** [comment]
This seems to run into the same failure as 3.0.2 (and 3.0.1). I raised an issue upstream.

**Review by pkgw — APPROVED** [review]
I'm not plugged in enough to the ops to feel comfortable merging in an update of such a fundamental package, but this PR looks good to me given the discussion.

**Comment by h-vetinari** [comment]
@hmaarrfk 
Would you mind pushing the button here as well? 🙃 
Thanks for your help!

PS. The commits https://github.com/conda-forge/openssl-feedstock/pull/83/commits/7ba0303aa55ace703d0665edd457454d6a1b8b28 .. https://github.com/conda-forge/openssl-feedstock/pull/83/commits/f4ea4c694a5eb3e4bd6fe4dc11a4ab227c84a694 are cherry-picked directly from main:

* 7ba0303aa55ace703d0665edd457454d6a1b8b28 -> 07871f3d281d9e37ead3154e02857694ffbe530b + 30a0d216c44141a2701991d91b2426ad207a6002
* 8dfce3fb1f57d2ccb00317354ac7f9ee6a5f03dd -> 46e5e81eb5bb8da33224ff0c6687645504062112
* 15ce3bc2f9d98f3b3989397821bc490386d47480 -> 32cc2b6f359c43c31a8dca2f1827fb394061ecfb
* 364e8c38ea65ff49ee2819c64eaacf5010a6e7e6 -> 4971beadf7eeb69c8d4eb0f8d0fb52bcbc11486d
* e6270dbf498266b9e396891e518ec0c0d82fdb47 -> 276cd8f1b6813e147d8e2f3fc285776e62d1cafe
* 953e350e60ce492cca417f9ccec882ef3a8c79e2 -> 81e334820bd5e232ac44a102941637389e1d1776
* f4ea4c694a5eb3e4bd6fe4dc11a4ab227c84a694 -> f1b38b7be5209e4a9052ec8aa238ef2f069949f9

**Review by jakirkham — APPROVED** [review]

**Pull request merged**
