### PR TITLE
openssl v3.0.1 (no patches)

### PR DESCRIPTION
**Pull request by duncanmmacleod**
This PR is a copy of #78 with an extra commit to remove the patches that are now upstream.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by duncanmmacleod** [comment]
@conda-forge/openssl, can this be merged (or labelled for automerge)?

**Comment by duncanmmacleod** [comment]
Gah, so close, one test is failing on linux-aarch64 (emulated from linux-64):

```console
Test Summary Report
-------------------
30-test_afalg.t                  (Wstat: 256 Tests: 1 Failed: 1)
  Failed test:  1
  Non-zero exit status: 1
Files=242, Tests=3419, 6600 wallclock secs (52.09 usr  1.05 sys + 6296.30 cusr 283.34 csys = 6632.78 CPU)
Result: FAIL
```

**Comment by ngam** [comment]
@conda-forge-admin, please rerender and pray for @duncanmmacleod 🙏

**Comment by ngam** [comment]
☠️ prayers didn't work...

**Pull request closed without merging**
