### PR TITLE
Remove fips provider

### LINKED ISSUE #104: Disable FIPS or move it to separate output
See comment from cryptography devs [here](https://github.com/pyca/cryptography/issues/7379#issuecomment-1177411842). I saw no harm in packaging it, but since it doesn't seem functional, we might as well save space/bandwidth for all those that don't need it.

### PR DESCRIPTION
**Pull request by h-vetinari**
Closes #104 

We almost certainly shouldn't be trying to build the FIPS provider (noted also by the cryptography dev's, see #104), as our builds aren't covered (AFAIU now) by the relevant approvals, and people with such stringent regulatory requirements almost certainly will not be using conda anyway.

When I opened #72, I didn't want to create too many changes, but I'm pretty certain now that  leaving in `enable-ssl2` was what caused the difference in behaviour (re: having a loadable legacy provider) between unix and windows that had me stumped as to why it didn't work on windows. So I decided to clean up and harmonize the options some more, for good.

~While I'm cleaning up the config options, I don't see why we shouldn't build zlib support. The [PR](https://github.com/conda-forge/openssl-feedstock/pull/20) that added `no-zlib` support doesn't explain why, but I don't think this can hurt these days, and also makes it easier to avoid the "empty-host-section-gets-interpreted-as-cb2" problem.~ See [below](https://github.com/conda-forge/openssl-feedstock/pull/105#issuecomment-1188278789)

I wanted to try all that to have a common set of options to test https://github.com/conda-forge/cryptography-feedstock/pull/98 against, before I'll most likely have to raise an upstream issue about the windows memory leaks.

### CODE REVIEW

**Comment by h-vetinari** [comment]
Interestingly, zlib support fails the test suite:
```
Test Summary Report
-------------------
80-test_cms.t                    (Wstat: 256 Tests: 12 Failed: 1)
  Failed test:  5
  Non-zero exit status: 1
80-test_ssl_new.t                (Wstat: 256 Tests: 30 Failed: 1)
  Failed test:  22
  Non-zero exit status: 1
80-test_ssl_old.t                (Wstat: 256 Tests: 6 Failed: 1)
  Failed test:  3
  Non-zero exit status: 1
Files=243, Tests=2874, 307 wallclock secs ( 4.31 usr  0.56 sys + 249.81 cusr 44.84 csys = 299.52 CPU)
Result: FAIL
```

No time for this though, can be solved separately

<details>

```
[...]
80-test_ca.t ....................... ok
80-test_cipherbytes.t .............. ok
80-test_cipherlist.t ............... ok
80-test_ciphername.t ............... ok

#
Killing mock server with pid=4273980-test_cmp_http.t ................. ok

    # CMD: openssl cms -provider-path ../../providers -provider default -compress -in ../../test/smcont.txt -outform PEM -nodetach -stream -out cms2cms-comp-1.cms
Warning: -nodetach option is ignored for non-signing operation
../../util/wrap.pl ../../apps/openssl cms -provider-path ../../providers -provider default -compress -in ../../test/smcont.txt -outform PEM -nodetach -stream -out cms2cms-comp-1.cms => 139
    # CMD: openssl cms -provider-path ../../providers -provider default -uncompress -in cms2cms-comp-1.cms -inform PEM -out cms2cms-comp-1.txt
    not ok 14 - compressed content test streaming PEM format
# ------------------------------------------------------------------------------
    #   Failed test 'compressed content test streaming PEM format'
    #   at test/recipes/80-test_cms.t line 668.
    # Looks like you failed 1 test of 14.
not ok 5 - CMS <=> CMS consistency tests, modified key parameters
# ------------------------------------------------------------------------------
#
# Looks like you failed 1 test of 12.80-test_cms.t ......................
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/12 subtests
80-test_cmsapi.t ................... ok
80-test_ct.t ....................... ok
80-test_dane.t ..................... ok
80-test_dtls.t ..................... ok
80-test_dtls_mtu.t ................. ok
80-test_dtlsv1listen.t ............. ok
80-test_ocsp.t ..................... ok
80-test_pkcs12.t ................... ok

../../util/wrap.pl ../../test/ssl_test 22-compression.cnf.default default => 139
    not ok 6 - running ssl_test 22-compression.cnf
    #   Failed test 'running ssl_test 22-compression.cnf'
    #   at test/recipes/80-test_ssl_new.t line 171.
    # Looks like you failed 2 tests of 6.
not ok 22 - Test configuration 22-compression.cnf
# ------------------------------------------------------------------------------
# Looks like you failed 1 test of 30.80-test_ssl_new.t ..................
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/30 subtests

    # Testing ciphersuites for -tls1_3
40E7F598BC7F0000:error:1280006C:DSO support routines:DSO_load:functionality not supported:crypto/dso/dso_lib.c:148:
40E7F598BC7F0000:error:0A0000B9:SSL routines:SSL_CTX_set_cipher_list:no cipher match:ssl/ssl_lib.c:2746:
Available compression methods:  zlib compression:1
../../util/wrap.pl ../../test/ssl_old_test -s_key ../../test/certs/ee-key.pem -s_cert certU.ss -c_key ../../test/certs/ee-key.pem -c_cert certU.ss -config ../../test/default-and-legacy.cnf -provider default -provider legacy -s_cert certD.ss -s_key keyD.ss -s_cert certE.ss -s_key keyE.ss -cipher '' -ciphersuites TLS_AES_256_GCM_SHA384 => 1
    not ok 120 - Testing
# ------------------------------------------------------------------------------
    #   Failed test 'Testing '
    #   at test/recipes/80-test_ssl_old.t line 507.
40273ABE167F0000:error:1280006C:DSO support routines:DSO_load:functionality not supported:crypto/dso/dso_lib.c:148:
40273ABE167F0000:error:0A0000B9:SSL routines:SSL_CTX_set_cipher_list:no cipher match:ssl/ssl_lib.c:2746:
Available compression methods:  zlib compression:1
../../util/wrap.pl ../../test/ssl_old_test -s_key ../../test/certs/ee-key.pem -s_cert certU.ss -c_key ../../test/certs/ee-key.pem -c_cert certU.ss -config ../../test/default-and-legacy.cnf -provider default -provider legacy -s_cert certD.ss -s_key keyD.ss -s_cert certE.ss -s_key keyE.ss -cipher '' -ciphersuites TLS_CHACHA20_POLY1305_SHA256 => 1
    not ok 121 - Testing
# ------------------------------------------------------------------------------
    #   Failed test 'Testing '
    #   at test/recipes/80-test_ssl_old.t line 507.
40D71FF94D7F0000:error:1280006C:DSO support routines:DSO_load:functionality not supported:crypto/dso/dso_lib.c:148:
40D71FF94D7F0000:error:0A0000B9:SSL routines:SSL_CTX_set_cipher_list:no cipher match:ssl/ssl_lib.c:2746:
Available compression methods:  zlib compression:1
../../util/wrap.pl ../../test/ssl_old_test -s_key ../../test/certs/ee-key.pem -s_cert certU.ss -c_key ../../test/certs/ee-key.pem -c_cert certU.ss -config ../../test/default-and-legacy.cnf -provider default -provider legacy -s_cert certD.ss -s_key keyD.ss -s_cert certE.ss -s_key keyE.ss -cipher '' -ciphersuites TLS_AES_128_GCM_SHA256 => 1
    not ok 122 - Testing
# ------------------------------------------------------------------------------
    #   Failed test 'Testing '
    #   at test/recipes/80-test_ssl_old.t line 507.
    # Looks like you failed 3 tests of 122.
not ok 3 - Testing ciphersuites
# ------------------------------------------------------------------------------
# Looks like you failed 1 test of 6.80-test_ssl_old.t ..................
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/6 subtests
80-test_ssl_test_ctx.t ............. ok
80-test_sslcorrupt.t ............... ok
[...]
```

</details>

**Comment by h-vetinari** [comment]
@conda-forge/openssl PTAL

As mentioned in the OP:
> I wanted to try all that to have a common set of options to test [conda-forge/cryptography-feedstock#98](https://github.com/conda-forge/cryptography-feedstock/pull/98) against, before I'll most likely have to raise an upstream issue about the windows memory leaks.

**Comment by h-vetinari** [comment]
Ping @conda-forge/openssl

**Comment by h-vetinari** [comment]
Gentle ping @conda-forge/openssl

**Comment by hmaarrfk** [comment]
>  our builds aren't covered (AFAIU now) by the relevant approvals, and people with such stringent regulatory requirements almost certainly will not be using conda anyway.

I'm not sure what approvals you mean. Upstream mentions audit requirements. That is different than an "approval" unless that is what you meant as well.


I don't understand why conda can't and shouldn't be used by people looking to get audited. That can actually help to be beneficial in building out packages right.

In either case, is it just a broken test? In that case, why not just skip the test with a note.

**Comment by h-vetinari** [comment]
Basically, FIPS is for sensitive US government agencies and getting any setup approved as compliant is a massive undertaking. Whether something packaged by conda-forge could even begin to be considered compliant would realistically also have to go through an expensive and time-consuming audit by a FIPS lab, which is never going to happen. Given that, it might actually be harmful to provide the illusion of compliance.

I didn't realize the full implications at the time, it mostly seemed like one more thing to build, so I proposed to do it, and it was merged. But for example, cryptography will not even pick up the FIPS provider unless activated in a very roundabout way (and that's intentional AFAICT). I don't think we should do that, or at the very least not by default.

All things considered, I trust the pyca folks when they say we shouldn't package for FIPS, because they understand this (big and scary) space way way better than I (and arguably most of conda-forge, even core) do.

Perhaps I may be permitted to ping @reaperhulk and @alex to confirm.

**Comment by alex** [comment]
Yeah, that all sounds right to me.

I think the shortest summary is: just building the FIPS provider with OpenSSL isn't nearly all that's required if you are in a position where FIPS compliance is mandated.

**Comment by h-vetinari** [comment]
> In either case, is it just a broken test? In that case, why not just skip the test with a note.

The tests are actually failing in cryptography, not openssl (forget the comment above about zlib integration, that's a distraction for the moment). But since those are memory leaks, I am not comfortable for several reasons to skip those.

The pyca folks have been willing to take a look but it's hard to root-cause, and so I want to raise an issue upstream. But before I do that, I want to trim the build down to the minimum we need (hence e.g. nofips), to avoid unnecessary noise while working towards finally wrapping up the openssl 3.0 migration in conda-forge.

**Comment by reaperhulk** [comment]
As someone who deals with FIPS both professionally and in my open source guise I will second that FIPS posture is a very complex item. Shipping the openssl provider in conda isn’t going to help very much and will likely confuse folks who have genuine compliance requirements.

**Comment by hmaarrfk** [comment]
Understood

**Comment by h-vetinari** [comment]
@conda-forge/core 
I've been trying to get the feedstock team to look at or merge this for two weeks now - could someone please have a look? 

As mentioned in the OP, the main goal here is:

> I wanted to try all that to have a common set of options to test [conda-forge/cryptography-feedstock#98](https://github.com/conda-forge/cryptography-feedstock/pull/98) against, before I'll most likely have to raise an upstream issue about the windows memory leaks.

... so that we can _finally_ move forward on the OpenSSL 3 migration.

**Comment by beckermr** [comment]
Add yourself to the recipe @h-vetinari so you can respond to any issues in the pr and I'd be happy to merge.

**Comment by h-vetinari** [comment]
> Add yourself to the recipe @h-vetinari so you can respond to any issues in the pr and I'd be happy to merge.

I'll admit I've always hesitated to add myself to openssl due to the perceived responsibility, but I guess it's time to bite that bullet...

**Comment by djhoese** [comment]
I was going to file a new issue about this, but seeing as this PR is only semi-recently closed: I release some software that uses `conda-pack` to make a tarball of a conda-forge-based environment and recently some users have tried to run the software on FIPS-enabled/limited machines. It doesn't seem like it will be an urgent requirement for me to make it work and I can always rebuild things that are necessary, but I just wanted to put my name in the bowl of people who use conda-forge and have users on FIPS machines.

Put another way, I'm not looking for certification, I just need the system's kernel to not panic/abort if it sees my non-FIPS OpenSSL version. The next level above that would be not failing a utility scanning my bundled package for non-FIPS software.

**Comment by h-vetinari** [comment]
> Put another way, I'm not looking for certification, I just need the system's kernel to not panic/abort if it sees my non-FIPS OpenSSL version. The next level above that would be not failing a utility scanning my bundled package for non-FIPS software.

Hey @djhoese, I think it's still better to file an issue about this - closed PRs tend to not be very visible.

I'm not opposed to having a separate output `openssl-fips`, but I'm not super comfortable with the idea for all the reasons laid out above.

**Pull request merged**
