### PR TITLE
Update to 1.0.2l

### PR DESCRIPTION
**Pull request by jschueller**
weird, 1.0.2k windows binaries are not currently published

### CODE REVIEW

**Comment by jakirkham** [comment]
> weird, 1.0.2k windows binaries are not currently published

Indeed. Triggered it manually. Please let me know whether it works.

ref: https://ci.appveyor.com/project/conda-forge/openssl-feedstock/build/1.0.25

**Comment by jschueller** [comment]
ping

**Comment by jschueller** [comment]
ping

**Comment by jschueller** [comment]
Could a maintainer merge this ?

**Comment by mingwandroid** [comment]
2nd'ed. Please merge.

**Comment by jakirkham** [comment]
Sorry have been otherwise preoccupied.

**Pull request merged**
